@startuml
left to right direction
skinparam packageStyle rectangle

rectangle  LPan


rectangle 用户模块{
    LPan -- 用户模块
}
rectangle 邮箱注册{
    用户模块 - 邮箱注册
}
database redis[
    redis缓存
]
redis ->验证码有效期
redis ->验证码每日上限
邮箱注册 -> redis
rectangle 验证码有效期{
}
rectangle 验证码每日上限{
}
rectangle 个人资料详情{
    用户模块  -- 个人资料详情
}




rectangle 存储管理{
    LPan -- 存储管理
}
database mysql[
mysql存储文件信息
]
mysql <- 存储管理

下载管理->mysql:根据信息找到文件



rectangle 文件管理{
    LPan -- 文件管理
}
rectangle 文件管理{
   文件管理--文件共享
   文件管理--文件修改
   文件管理--文件上传
}
rectangle 文件修改{
}
rectangle 文件上传{
 }
rectangle 文件共享{
    文件共享 -- 权限管理
}
rectangle 权限管理 {
    权限管理--加密链接
    权限管理--二维码分享
}
rectangle 加密链接{
}
rectangle 二维码分享{
}



rectangle 下载管理{
    LPan---下载管理
}
rectangle 限速{
   下载管理--限速
}
rectangle 边下边播{
   下载管理--边下边播
}
rectangle 断点续传{
   下载管理--断点续传
}

@enduml